# References

[NeRF Benchmark Datasets](http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV20/nerf/nerf_example_data.zip)

[NeRF Pytorch Implementation](https://github.com/yenchenlin/nerf-pytorch)

[Original COLMAP Implementation](https://github.com/colmap/colmap)

[Google Colab COLMAP Implementation](https://github.com/Abbsalehi/colmap)

[LLFF Pose Generator](https://github.com/Fyusion/LLFF)

---

# 1. Photo Collection

- Take ~20 Photos of an object in good lighting.
- put the photos in a folder name `images`
- put the `images` folder in a different folder named after your subject to run colmap.
- put that folder in the data folder in `nerf_pytorch/data`

In [15]:
# Google Drive is formatted "/content/drive/My Drive/.../.../..."
basedir = "/content/drive/My Drive/cs117/final_project/nerf_pytorch/data/peter_scaled" # do not include '/images'!!

---

# 2. COLMAP

colmap is a structure from motion algorithm. It will derrive relative coordinates of the camera's position in each photo.

Unfortunately, colmap has many UI elements that Google Colab cannot support. Special Thanks to [Abbas Salehi](https://github.com/Abbsalehi) for providing code to build colmap from source that excludes these elements.

### Install the required packages

In [2]:
!sudo apt-get install -y git
!sudo apt-get install -y cmake
!sudo apt-get install -y ninja-build
!sudo apt-get install -y build-essential
!sudo apt-get install -y libboost-program-options-dev
!sudo apt-get install -y libboost-filesystem-dev
!sudo apt-get install -y libboost-graph-dev
!sudo apt-get install -y libboost-system-dev
!sudo apt-get install -y libeigen3-dev
!sudo apt-get install -y libflann-dev
!sudo apt-get install -y libfreeimage-dev
!sudo apt-get install -y libmetis-dev
!sudo apt-get install -y libgoogle-glog-dev
!sudo apt-get install -y libgtest-dev
!sudo apt-get install -y libsqlite3-dev
!sudo apt-get install -y libglew-dev
!sudo apt-get install -y qtbase5-dev
!sudo apt-get install -y libqt5opengl5-dev
!sudo apt-get install -y libcgal-dev
!sudo apt-get install -y libceres-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ninja-build
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 111 kB of archives.
After this operation, 358 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ninja-build amd64 1.10.1-1 [111 kB]
Fetched 111 kB in 1s (124 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the 

### Clone Colmap repsitory

In [3]:
!pwd
!git clone https://github.com/colmap/colmap.git
%cd colmap

/content
Cloning into 'colmap'...
remote: Enumerating objects: 23644, done.
remote: Counting objects: 100% (2569/2569), done.
remote: Compressing objects: 100% (1340/1340), done.
remote: Total 23644 (delta 1569), reused 2036 (delta 1220), pack-reused 21075 (from 1)
Receiving objects: 100% (23644/23644), 70.00 MiB | 17.09 MiB/s, done.
Resolving deltas: 100% (18042/18042), done.
/content/colmap


### Build and install Colmap from source


In [4]:
!pwd
!mkdir build
%cd build
!cmake -GNinja ..
!ninja
!sudo ninja install

/content/colmap
/content/colmap/build
-- Enabling LSD support
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found FreeImage
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Found FLANN
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
-- Found LZ4
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
-- Found Metis
--   Includes : /usr/include
--   Libraries : /usr/lib/x86_64-linux-gnu/libmetis.so
-- Found Glog
--   Target : glog:

### Allow access to Google Drive

In [5]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


### Detect and extract features from images for matching

In [16]:
!colmap feature_extractor \
    --database_path "{basedir}/database.db" \
    --image_path "{basedir}/images" \
    --ImageReader.single_camera 1

I1209 20:26:10.487676 16648 misc.cc:44] 
Feature extraction
I1209 20:26:10.488457 16651 sift.cc:721] Creating SIFT GPU feature extractor
I1209 20:26:12.129238 16652 feature_extraction.cc:258] Processed file [1/20]
I1209 20:26:12.129278 16652 feature_extraction.cc:261]   Name:            IMG_0132.jpg
I1209 20:26:12.129287 16652 feature_extraction.cc:270]   Dimensions:      1008 x 756
I1209 20:26:12.129294 16652 feature_extraction.cc:273]   Camera:          #1 - SIMPLE_RADIAL
I1209 20:26:12.129303 16652 feature_extraction.cc:276]   Focal Length:    1209.60px
I1209 20:26:12.129333 16652 feature_extraction.cc:280]   Features:        4897
I1209 20:26:15.073046 16652 feature_extraction.cc:258] Processed file [2/20]
I1209 20:26:15.073082 16652 feature_extraction.cc:261]   Name:            IMG_0133.jpg
I1209 20:26:15.073092 16652 feature_extraction.cc:270]   Dimensions:      1008 x 756
I1209 20:26:15.073100 16652 feature_extraction.cc:273]   Camera:          #1 - SIMPLE_RADIAL
I1209 20:26:15.0

### Match features between all pairs of images

In [17]:
!colmap exhaustive_matcher\
    --database_path "{basedir}/database.db"

I1209 20:26:41.408154 16785 misc.cc:44] 
Feature matching
I1209 20:26:41.409587 16786 sift.cc:1426] Creating SIFT GPU feature matcher
I1209 20:26:41.562206 16785 pairing.cc:168] Generating exhaustive image pairs...
I1209 20:26:41.562247 16785 pairing.cc:201] Matching block [1/1, 1/1]
I1209 20:26:44.115427 16785 feature_matching.cc:46] in 2.553s
I1209 20:26:44.180395 16785 timer.cc:91] Elapsed time: 0.046 [minutes]


### Reconstruct camera poses and scene geometry:

- At this step, make a folder named `sparse` in your drive in the same basedir (where your `images` folder is)

In [18]:
!colmap mapper \
    --database_path "{basedir}/database.db" \
    --image_path "{basedir}/images" \
    --output_path "{basedir}/sparse" \
    --Mapper.num_threads 16 \
    --Mapper.init_min_tri_angle 4 \
    --Mapper.multiple_models 0 \
    --Mapper.extract_colors 0

I1209 20:27:13.234179 16929 incremental_pipeline.cc:237] Loading database
I1209 20:27:13.285725 16929 database_cache.cc:66] Loading cameras...
I1209 20:27:13.285804 16929 database_cache.cc:76]  1 in 0.000s
I1209 20:27:13.285823 16929 database_cache.cc:84] Loading matches...
I1209 20:27:13.339946 16929 database_cache.cc:89]  190 in 0.054s
I1209 20:27:13.339982 16929 database_cache.cc:105] Loading images...
I1209 20:27:13.376948 16929 database_cache.cc:153]  20 in 0.037s (connected 20)
I1209 20:27:13.376987 16929 database_cache.cc:164] Loading pose priors...
I1209 20:27:13.377112 16929 database_cache.cc:175]  0 in 0.000s
I1209 20:27:13.377126 16929 database_cache.cc:184] Building correspondence graph...
I1209 20:27:13.404840 16929 database_cache.cc:210]  in 0.028s (ignored 0)
I1209 20:27:13.404907 16929 timer.cc:91] Elapsed time: 0.002 [minutes]
I1209 20:27:13.416846 16929 incremental_pipeline.cc:282] Finding good initial image pair
I1209 20:27:13.493727 16929 incremental_pipeline.cc:306

### Load and Save results from colmap [(code source)](https://github.com/Fyusion/LLFF/blob/master/llff/poses/pose_utils.py)

In [19]:
import sys
sys.path.append('/content/drive/My Drive/cs117/final_project/LLFF')
from llff.poses.pose_utils import load_colmap_data, save_poses

In [20]:
poses, pts3d, perm = load_colmap_data(basedir)
save_poses(basedir, poses, pts3d, perm)

Cameras 5
Images # 20
Points (7710, 3) Visibility (7710, 20)
Depth stats 10.684746196558311 204.43804335338632 30.7489038139925


---

# 3. Train


### import train function [(modified version of this)](https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf.py)

In [21]:
import sys
import argparse
sys.path.append('/content/drive/My Drive/cs117/final_project/nerf_pytorch')
from run_nerf import train, generate_render

### Training Arguments Description

- **basedir**: The directory where checkpoints and logs will be stored.
- **datadir**: The input data directory containing the dataset to be trained on.
- **config**: The path to the configuration file containing training parameters and settings.

- **no_reload**: If `True`, prevents reloading weights from a saved checkpoint. Initial value was `False`.
- **ft_path**: Path to a specific weights tar file to reload for the coarse network.

- **dataset_type**: Type of dataset to be used. Options include `llff`, `blender`, and `deepvoxels`. Initial value was `llff`.
- **expname**: A name for the experiment.

- **N_iters**: Number of iterations (training steps). Initial value was `200000`.
- **i_img**: Frequency for tensorboard image logging. Set to an arbitrarily high number to disable. Initial value was `500`.
- **i_print**: Frequency of console printouts and metric logging. Initial value was `100`.
- **i_weights**: Frequency of saving weight checkpoints. Initial value was `10000`.

- **half_res**: If `True`, loads Blender synthetic data at 400x400 resolution instead of 800x800. Initial value was `False`.


In [22]:
train_args = argparse.Namespace(
        basedir='/content/drive/My Drive/cs117/final_project/nerf_pytorch/logs',
        datadir='/content/drive/My Drive/cs117/final_project/nerf_pytorch/data/peter_scaled',
        config='/content/drive/My Drive/cs117/final_project/nerf_pytorch/configs/fern.txt',

        no_reload=True,
        ft_path= '',

        dataset_type='llff',
        expname='peter_anteater_test_1008_756',

        N_iters=200001,
        i_img=999999999,
        i_print=100,
        i_weights= 1000,

        half_res=False,
    )

### train model

In [ ]:
train(train_args)

/usr/local/lib/python3.10/dist-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)


Loaded image data (756, 1008, 3, 20) [ 756.         1008.          775.22847338]
Loaded /content/drive/My Drive/cs117/final_project/nerf_pytorch/data/peter_scaled 10.72454406271616 143.13547937598503
recentered (3, 5)
[[ 1.0000000e+00 -2.7986127e-10  7.4733131e-10  7.4505806e-09]
 [ 2.7986127e-10  1.0000000e+00  1.8683284e-09 -2.0861625e-08]
 [-7.4733125e-10 -1.8683284e-09  1.0000000e+00  2.9802323e-09]]
Data:
(20, 3, 5) (20, 756, 1008, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 756, 1008, 3) (60, 3, 5) [ 756.      1008.       775.22845] /content/drive/My Drive/cs117/final_project/nerf_pytorch/data/peter_scaled
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['']
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19]
TEST views are [ 0  8 16]
VAL views are [ 0  8 16]


  0%|          | 0/200001 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


[Config] Center cropping of size 378 x 504 is enabled until iter 500


  0%|          | 100/200001 [00:35<19:14:05,  2.89it/s]

[TRAIN] Iter: 100 Loss: 0.06809207797050476  PSNR: 14.463050842285156


  0%|          | 200/200001 [01:10<20:08:12,  2.76it/s]

[TRAIN] Iter: 200 Loss: 0.05311751738190651  PSNR: 15.702400207519531


  0%|          | 300/200001 [01:48<21:04:26,  2.63it/s]

[TRAIN] Iter: 300 Loss: 0.046567026525735855  PSNR: 16.24085807800293


  0%|          | 400/200001 [02:25<20:18:34,  2.73it/s]

[TRAIN] Iter: 400 Loss: 0.03651077300310135  PSNR: 17.328338623046875


  0%|          | 500/200001 [03:01<20:53:18,  2.65it/s]

[TRAIN] Iter: 500 Loss: 0.0396135151386261  PSNR: 16.88314437866211


  0%|          | 600/200001 [03:40<21:47:56,  2.54it/s]

[TRAIN] Iter: 600 Loss: 0.030760610476136208  PSNR: 18.067625045776367


  0%|          | 700/200001 [04:19<21:41:27,  2.55it/s]

[TRAIN] Iter: 700 Loss: 0.026381686329841614  PSNR: 18.709993362426758


  0%|          | 800/200001 [04:57<21:36:30,  2.56it/s]

[TRAIN] Iter: 800 Loss: 0.02369772270321846  PSNR: 19.124902725219727


  0%|          | 900/200001 [05:36<21:11:19,  2.61it/s]

[TRAIN] Iter: 900 Loss: 0.020897850394248962  PSNR: 19.568498611450195


  0%|          | 1000/200001 [06:14<22:29:02,  2.46it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/001000.tar
[TRAIN] Iter: 1000 Loss: 0.02290312945842743  PSNR: 19.298973083496094


  1%|          | 1100/200001 [06:53<21:05:08,  2.62it/s]

[TRAIN] Iter: 1100 Loss: 0.025471944361925125  PSNR: 18.87071418762207


  1%|          | 1200/200001 [07:31<20:58:48,  2.63it/s]

[TRAIN] Iter: 1200 Loss: 0.020098520442843437  PSNR: 19.899131774902344


  1%|          | 1300/200001 [08:10<21:20:11,  2.59it/s]

[TRAIN] Iter: 1300 Loss: 0.021332155913114548  PSNR: 19.67839241027832


  1%|          | 1400/200001 [08:48<21:23:58,  2.58it/s]

[TRAIN] Iter: 1400 Loss: 0.020954513922333717  PSNR: 19.671960830688477


  1%|          | 1500/200001 [09:26<21:16:38,  2.59it/s]

[TRAIN] Iter: 1500 Loss: 0.021419618278741837  PSNR: 19.66583824157715


  1%|          | 1600/200001 [10:05<21:35:04,  2.55it/s]

[TRAIN] Iter: 1600 Loss: 0.02130361832678318  PSNR: 19.698259353637695


  1%|          | 1700/200001 [10:43<21:21:01,  2.58it/s]

[TRAIN] Iter: 1700 Loss: 0.01672944985330105  PSNR: 20.813461303710938


  1%|          | 1800/200001 [11:21<20:57:43,  2.63it/s]

[TRAIN] Iter: 1800 Loss: 0.01914488896727562  PSNR: 20.24941062927246


  1%|          | 1900/200001 [12:00<20:56:37,  2.63it/s]

[TRAIN] Iter: 1900 Loss: 0.01953674480319023  PSNR: 20.263097763061523


  1%|          | 2000/200001 [12:38<22:25:04,  2.45it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/002000.tar
[TRAIN] Iter: 2000 Loss: 0.01589815504848957  PSNR: 20.903961181640625


  1%|          | 2100/200001 [13:16<20:56:30,  2.63it/s]

[TRAIN] Iter: 2100 Loss: 0.023086152970790863  PSNR: 19.436874389648438


  1%|          | 2200/200001 [13:54<21:03:25,  2.61it/s]

[TRAIN] Iter: 2200 Loss: 0.016101546585559845  PSNR: 21.034473419189453


  1%|          | 2300/200001 [14:33<21:21:39,  2.57it/s]

[TRAIN] Iter: 2300 Loss: 0.016611674800515175  PSNR: 20.944108963012695


  1%|          | 2400/200001 [15:11<21:42:01,  2.53it/s]

[TRAIN] Iter: 2400 Loss: 0.014692168682813644  PSNR: 21.391448974609375


  1%|          | 2500/200001 [15:49<21:31:06,  2.55it/s]

[TRAIN] Iter: 2500 Loss: 0.01565409265458584  PSNR: 21.389930725097656


  1%|▏         | 2600/200001 [16:27<20:57:11,  2.62it/s]

[TRAIN] Iter: 2600 Loss: 0.014888817444443703  PSNR: 21.290002822875977


  1%|▏         | 2700/200001 [17:06<20:51:38,  2.63it/s]

[TRAIN] Iter: 2700 Loss: 0.015765322372317314  PSNR: 21.17599868774414


  1%|▏         | 2800/200001 [17:44<20:51:33,  2.63it/s]

[TRAIN] Iter: 2800 Loss: 0.0201763566583395  PSNR: 20.0804443359375


  1%|▏         | 2900/200001 [18:22<20:52:54,  2.62it/s]

[TRAIN] Iter: 2900 Loss: 0.019988102838397026  PSNR: 20.05316162109375


  1%|▏         | 3000/200001 [19:00<22:03:41,  2.48it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/003000.tar
[TRAIN] Iter: 3000 Loss: 0.020146731287240982  PSNR: 20.21322250366211


  2%|▏         | 3100/200001 [19:39<20:58:54,  2.61it/s]

[TRAIN] Iter: 3100 Loss: 0.015766387805342674  PSNR: 21.293720245361328


  2%|▏         | 3200/200001 [20:17<21:26:46,  2.55it/s]

[TRAIN] Iter: 3200 Loss: 0.01586979627609253  PSNR: 21.4323787689209


  2%|▏         | 3300/200001 [20:55<21:26:15,  2.55it/s]

[TRAIN] Iter: 3300 Loss: 0.0138819245621562  PSNR: 21.74393081665039


  2%|▏         | 3400/200001 [21:33<20:47:21,  2.63it/s]

[TRAIN] Iter: 3400 Loss: 0.014795362018048763  PSNR: 21.73024559020996


  2%|▏         | 3500/200001 [22:11<20:52:57,  2.61it/s]

[TRAIN] Iter: 3500 Loss: 0.013192364946007729  PSNR: 21.9428768157959


  2%|▏         | 3600/200001 [22:50<20:38:40,  2.64it/s]

[TRAIN] Iter: 3600 Loss: 0.015536542981863022  PSNR: 21.015316009521484


  2%|▏         | 3700/200001 [23:28<20:45:56,  2.63it/s]

[TRAIN] Iter: 3700 Loss: 0.012409256771206856  PSNR: 22.25955581665039


  2%|▏         | 3800/200001 [24:06<20:46:58,  2.62it/s]

[TRAIN] Iter: 3800 Loss: 0.014546644873917103  PSNR: 21.90918731689453


  2%|▏         | 3900/200001 [24:44<20:58:31,  2.60it/s]

[TRAIN] Iter: 3900 Loss: 0.016722314059734344  PSNR: 21.299985885620117


  2%|▏         | 4000/200001 [25:22<22:45:22,  2.39it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/004000.tar
[TRAIN] Iter: 4000 Loss: 0.013056473806500435  PSNR: 22.082103729248047


  2%|▏         | 4100/200001 [26:00<21:15:54,  2.56it/s]

[TRAIN] Iter: 4100 Loss: 0.013812823221087456  PSNR: 21.65818214416504


  2%|▏         | 4200/200001 [26:38<21:08:19,  2.57it/s]

[TRAIN] Iter: 4200 Loss: 0.01656007394194603  PSNR: 21.364049911499023


  2%|▏         | 4300/200001 [27:17<20:58:19,  2.59it/s]

[TRAIN] Iter: 4300 Loss: 0.012209329754114151  PSNR: 22.212793350219727


  2%|▏         | 4400/200001 [27:55<20:45:01,  2.62it/s]

[TRAIN] Iter: 4400 Loss: 0.015030203387141228  PSNR: 21.392080307006836


  2%|▏         | 4500/200001 [28:33<20:36:20,  2.64it/s]

[TRAIN] Iter: 4500 Loss: 0.01547196228057146  PSNR: 21.302860260009766


  2%|▏         | 4600/200001 [29:11<20:40:46,  2.62it/s]

[TRAIN] Iter: 4600 Loss: 0.014258778654038906  PSNR: 21.774715423583984


  2%|▏         | 4700/200001 [29:49<20:35:18,  2.63it/s]

[TRAIN] Iter: 4700 Loss: 0.01347361784428358  PSNR: 21.941722869873047


  2%|▏         | 4800/200001 [30:27<20:36:42,  2.63it/s]

[TRAIN] Iter: 4800 Loss: 0.014255553483963013  PSNR: 21.789640426635742


  2%|▏         | 4900/200001 [31:05<20:34:44,  2.63it/s]

[TRAIN] Iter: 4900 Loss: 0.015794482082128525  PSNR: 21.280841827392578


  2%|▏         | 5000/200001 [31:43<22:16:36,  2.43it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/005000.tar
[TRAIN] Iter: 5000 Loss: 0.012664551846683025  PSNR: 22.201066970825195


  3%|▎         | 5100/200001 [32:21<21:13:24,  2.55it/s]

[TRAIN] Iter: 5100 Loss: 0.014518821612000465  PSNR: 21.65078353881836


  3%|▎         | 5200/200001 [32:59<20:56:03,  2.58it/s]

[TRAIN] Iter: 5200 Loss: 0.012132838368415833  PSNR: 22.355571746826172


  3%|▎         | 5300/200001 [33:37<20:38:48,  2.62it/s]

[TRAIN] Iter: 5300 Loss: 0.010560457594692707  PSNR: 23.036745071411133


  3%|▎         | 5400/200001 [34:15<20:29:33,  2.64it/s]

[TRAIN] Iter: 5400 Loss: 0.012208255007863045  PSNR: 22.68987274169922


  3%|▎         | 5500/200001 [34:53<20:28:17,  2.64it/s]

[TRAIN] Iter: 5500 Loss: 0.012966649606823921  PSNR: 22.31229019165039


  3%|▎         | 5600/200001 [35:31<20:30:31,  2.63it/s]

[TRAIN] Iter: 5600 Loss: 0.016033509746193886  PSNR: 21.102691650390625


  3%|▎         | 5700/200001 [36:09<20:35:13,  2.62it/s]

[TRAIN] Iter: 5700 Loss: 0.012734830379486084  PSNR: 22.257457733154297


  3%|▎         | 5800/200001 [36:47<20:32:01,  2.63it/s]

[TRAIN] Iter: 5800 Loss: 0.012853509746491909  PSNR: 22.309133529663086


  3%|▎         | 5900/200001 [37:25<20:30:57,  2.63it/s]

[TRAIN] Iter: 5900 Loss: 0.012291270308196545  PSNR: 22.391416549682617


  3%|▎         | 6000/200001 [38:03<22:01:48,  2.45it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/006000.tar
[TRAIN] Iter: 6000 Loss: 0.012552820146083832  PSNR: 22.37737274169922


  3%|▎         | 6100/200001 [38:41<21:08:15,  2.55it/s]

[TRAIN] Iter: 6100 Loss: 0.010894952341914177  PSNR: 22.90172004699707


  3%|▎         | 6200/200001 [39:19<21:05:08,  2.55it/s]

[TRAIN] Iter: 6200 Loss: 0.012966858223080635  PSNR: 22.188020706176758


  3%|▎         | 6300/200001 [39:57<20:30:20,  2.62it/s]

[TRAIN] Iter: 6300 Loss: 0.01177477277815342  PSNR: 22.329221725463867


  3%|▎         | 6400/200001 [40:35<20:26:48,  2.63it/s]

[TRAIN] Iter: 6400 Loss: 0.010494769550859928  PSNR: 23.094018936157227


  3%|▎         | 6500/200001 [41:13<20:29:18,  2.62it/s]

[TRAIN] Iter: 6500 Loss: 0.015151040628552437  PSNR: 21.429548263549805


  3%|▎         | 6600/200001 [41:51<20:17:29,  2.65it/s]

[TRAIN] Iter: 6600 Loss: 0.011852536350488663  PSNR: 22.43631935119629


  3%|▎         | 6700/200001 [42:29<20:11:58,  2.66it/s]

[TRAIN] Iter: 6700 Loss: 0.009901599958539009  PSNR: 23.291582107543945


  3%|▎         | 6800/200001 [43:07<20:23:39,  2.63it/s]

[TRAIN] Iter: 6800 Loss: 0.009544195607304573  PSNR: 23.672414779663086


  3%|▎         | 6900/200001 [43:45<20:30:57,  2.61it/s]

[TRAIN] Iter: 6900 Loss: 0.010593647137284279  PSNR: 23.086729049682617


  3%|▎         | 7000/200001 [44:23<21:52:49,  2.45it/s]

Saved checkpoints at /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/peter_anteater_test_1008_756/007000.tar
[TRAIN] Iter: 7000 Loss: 0.014144035056233406  PSNR: 21.46079444885254


  4%|▎         | 7100/200001 [45:00<20:44:27,  2.58it/s]

[TRAIN] Iter: 7100 Loss: 0.010619033128023148  PSNR: 23.020456314086914


  4%|▎         | 7153/200001 [45:20<20:04:05,  2.67it/s]

# 4. Render Images / Video



### Rendering Arguments Description

- **basedir**: The directory where checkpoints and logs will be stored.
- **datadir**: The input data directory containing the dataset to be rendered.
- **config**: The path to the configuration file containing rendering parameters and settings.
- **ft_path**: Path to a specific weights tar file to reload for the coarse network.

- **dataset_type**: Type of dataset to be used. Options include `llff`, `blender`, and `deepvoxels`. Initial value was `llff`.
- **expname**: A name for the experiment.

- **half_res**: If `True`, loads Blender synthetic data at 400x400 resolution instead of 800x800. Initial value was `False`.
- **num_frames**: Number of frames to generate. Initial value was `40`.




In [ ]:
render_args = argparse.Namespace(
        basedir='/content/drive/My Drive/cs117/final_project/nerf_pytorch/logs',
        datadir='/content/drive/My Drive/cs117/final_project/nerf_pytorch/data/fern',
        config='/content/drive/My Drive/cs117/final_project/nerf_pytorch/configs/fern.txt',
        ft_path= '/content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/fern_generated_test/004000.tar',

        dataset_type='llff',
        expname='fern_test',

        half_res=False,
        num_frames = 4,
    )

### generate render

In [ ]:
generate_render(render_args)

/usr/local/lib/python3.10/dist-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)


Loaded image data (3024, 4032, 3, 20) [3024.         4032.          412.43921666]
Loaded /content/drive/My Drive/cs117/final_project/nerf_pytorch/data/fern 17.27981027806605 81.97951962241297
recentered (3, 5)
[[ 1.0000000e+00  5.5785743e-10  2.9970979e-09  0.0000000e+00]
 [-5.5785743e-10  1.0000000e+00  2.4351421e-09  4.4703485e-09]
 [-2.9970979e-09 -2.4351421e-09  1.0000000e+00  1.8626452e-10]]
Data:
(20, 3, 5) (20, 3024, 4032, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 3024, 4032, 3) (4, 3, 5) [3024.     4032.      412.4392] /content/drive/My Drive/cs117/final_project/nerf_pytorch/data/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['/content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/fern_generated_test/004000.tar']
Reloading from /content/drive/My Drive/cs117/final_project/nerf_pytorch/logs/fern_generated_test/004000.tar


/content/drive/My Drive/cs117/final_project/nerf_pytorch/run_nerf.py:226: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(ckpt_path)


RENDER ONLY
test poses shape torch.Size([4, 3, 5])


  0%|          | 0/4 [00:00<?, ?it/s]

0 0.01110696792602539


/usr/local/lib/python3.10/dist-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


torch.Size([3024, 4032, 3]) torch.Size([3024, 4032])


 25%|██▌       | 1/4 [31:44<1:35:13, 1904.49s/it]

1 1904.4925382137299
